-- FinSight AI: Snowflake bootstrap. Safe to re-run (IF NOT EXISTS / OR REPLACE everywhere).
-- Run in Snowsight as a user that has ACCOUNTADMIN.
-- Before running: replace <YOUR_LOGIN_NAME> in section 5 with the result of SELECT CURRENT_USER();

-- 1. Compute ---------------------------------------------------------------
USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS FINSIGHT_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'FinSight ingestion, dbt and agent queries';

-- 2. Storage: one schema per layer ----------------------------------------
CREATE DATABASE IF NOT EXISTS FINSIGHT;
CREATE SCHEMA IF NOT EXISTS FINSIGHT.RAW     COMMENT = 'Source data, minimal transformation';
CREATE SCHEMA IF NOT EXISTS FINSIGHT.STAGING COMMENT = 'Cleaned, typed, deduplicated';
CREATE SCHEMA IF NOT EXISTS FINSIGHT.CORE    COMMENT = 'Reusable facts and dimensions';
CREATE SCHEMA IF NOT EXISTS FINSIGHT.MART    COMMENT = 'Business-ready models for analysts and the agent';

-- 3. Roles -----------------------------------------------------------------
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS FINSIGHT_ENGINEER COMMENT = 'Ingestion and dbt: read/write all layers';
CREATE ROLE IF NOT EXISTS FINSIGHT_AGENT    COMMENT = 'Text-to-SQL agent: read MART only';

USE ROLE SECURITYADMIN;
GRANT ROLE FINSIGHT_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE FINSIGHT_AGENT    TO ROLE SYSADMIN;

-- 4a. FINSIGHT_ENGINEER: read/write every layer -----------------------------
GRANT USAGE ON WAREHOUSE FINSIGHT_WH TO ROLE FINSIGHT_ENGINEER;
GRANT USAGE ON DATABASE FINSIGHT     TO ROLE FINSIGHT_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA FINSIGHT.RAW     TO ROLE FINSIGHT_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA FINSIGHT.STAGING TO ROLE FINSIGHT_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA FINSIGHT.CORE    TO ROLE FINSIGHT_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA FINSIGHT.MART    TO ROLE FINSIGHT_ENGINEER;

-- 4b. FINSIGHT_AGENT: read MART only, including tables created later --------
GRANT USAGE ON WAREHOUSE FINSIGHT_WH TO ROLE FINSIGHT_AGENT;
GRANT USAGE ON DATABASE FINSIGHT     TO ROLE FINSIGHT_AGENT;
GRANT USAGE ON SCHEMA FINSIGHT.MART  TO ROLE FINSIGHT_AGENT;
GRANT SELECT ON ALL TABLES    IN SCHEMA FINSIGHT.MART TO ROLE FINSIGHT_AGENT;
GRANT SELECT ON ALL VIEWS     IN SCHEMA FINSIGHT.MART TO ROLE FINSIGHT_AGENT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINSIGHT.MART TO ROLE FINSIGHT_AGENT;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA FINSIGHT.MART TO ROLE FINSIGHT_AGENT;

-- 5. Service user: key-pair only, no password -------------------------------
USE ROLE USERADMIN;
CREATE USER IF NOT EXISTS FINSIGHT_SVC
    TYPE = SERVICE
    DEFAULT_ROLE = FINSIGHT_ENGINEER
    DEFAULT_WAREHOUSE = FINSIGHT_WH
    COMMENT = 'Ingestion and dbt service user';
-- The public key is set separately (see README, "Snowflake setup"):
-- ALTER USER FINSIGHT_SVC SET RSA_PUBLIC_KEY = '<one-line public key>';

USE ROLE SECURITYADMIN;
GRANT ROLE FINSIGHT_ENGINEER TO USER FINSIGHT_SVC;
-- Let your own login switch into both roles for testing in Snowsight.
GRANT ROLE FINSIGHT_ENGINEER TO USER <YOUR_LOGIN_NAME>;
GRANT ROLE FINSIGHT_AGENT    TO USER <YOUR_LOGIN_NAME>;

-- 6. Account-wide settings and cost guard -----------------------------------
USE ROLE ACCOUNTADMIN;
-- Snowflake defaults to America/Los_Angeles; the whole project works in UTC.
ALTER ACCOUNT SET TIMEZONE = 'UTC';

CREATE OR REPLACE RESOURCE MONITOR FINSIGHT_MONTHLY_RM
    WITH CREDIT_QUOTA = 20
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 80 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE FINSIGHT_WH SET RESOURCE_MONITOR = FINSIGHT_MONTHLY_RM;
